### ISSUE TITLE
Odd log issues + Undefined index

### ISSUE THREAD

**Issue by jpobeda** [earendilfr/plugin_intropage#2]
Hi there,

I installed this plugin with Cacti 1.1.9 and I'm getting this error on apache logs

> [Tue Jun 06 14:15:18.552363 2017] [:error] [pid 5279] [client 143.96.129.128:51221] PHP Notice:  Undefined index:  in /usr/share/cacti-1.1.9/plugins/intropage/functions/hosts.php on line 148, referer: https://(...)/cacti/plugins.php

Along with this error I'm getting other logs entries on /var/log/httpd/error_log and they don't have nothing to do there because are Cacti logs from the poller. So I wonder how are they being redirected there every time I active this plugin.

Ideas?

One more thing

> Hint: You can choose view between separated tab and console, you can set it up in Console -> User Management -> User -> Intropage Options

It should really say Console -> Settings -> Intropage

BUT there is not such an option to put it on a TAB.

thanks for this nice plugin btw!

**Comment by earendilfr** [comment]
I have an idea: could you think you can sent me the output of the command 
`SELECT data_input.type_id, COUNT(data_input.type_id) AS total FROM data_local INNER JOIN data_template_data ON (data_local.id = data_template_data.local_data_id) LEFT JOIN data_input ON (data_input.id=data_template_data.data_input_id) LEFT JOIN data_template ON (data_local.data_template_id=data_template.id) WHERE local_data_id<>0 group by type_id LIMIT 6` 
in your CACTI Database?

I think I don't have take in count a type of return...

**Comment by jpobeda** [comment]
Hi Ambroise,

Here is the output

> +---------+-------+
> | type_id | total |
> +---------+-------+
> |    NULL |     0 |
> |       1 |     5 |
> |       2 |   119 |
> |       3 |  1842 |
> |       4 |    10 |
> |       5 |    74 |
> +---------+-------+
> 6 rows in set (0.01 sec)

**Comment by earendilfr** [comment]
Could you check with the commit 55732ce?

**Comment by jpobeda** [comment]
It worked!

Can you add the option to display it in a separated tab? Looks to be there but I think the array on variables.php is missing.

Thanks for the fix!

**Comment by earendilfr** [comment]
Normally, the option should be present not in the global configuration pane but in the user specific configuration pane (just bellow the login options).

Currently, I don't have introduce a global configuration 8it's only per users)

**Comment by jpobeda** [comment]
OK, I see, but still can't see the option. I'm running cacti-1.1.9 have you tested it?

Jesus...Just found it..it was under user settings but the general tab. Done, thanks and sorry for my lazy brain.

**Comment by jpobeda** [comment]
If I check "Allow cacti log analyse" option I get some logs from cacti.log on /var/log/httpd/error_log file.

This is odd I don't how's this being redirected to apache error log file.. Any ideas? Most of the logs are WEATHERMAP logs from cacti.log, I'm a bit confused.

**Comment by earendilfr** [comment]
For weathermap, I can't answer (the last time I have check, the plugin is still not compatible with Cacti v1.x)
For plugin_intropage, if you have still any log in error_log, could you just send me these messages? 

I'm really sure that I have still some issue with my PHP code...

**Comment by jpobeda** [comment]
Hi there,

Once I enable the "Allow cacti log analyse", every time I click on the Intropage tab I get these error on /var/log/httpd/error_log but they are not errors by mean. Those are log lines from Cacti.log for weathermap.
What I'm trying to understand is, intropage reads cacti.log file right? and those lines some how gets to the apache error log..

I manually edited the attached file to suppress sensitive data BUT it was also badly formatted, spaces everywhere.

If you look at the log, they are not weathermap errors even, those are only informative ones.

[intropage_httpd_error.txt](https://github.com/earendilfr/plugin_intropage/files/1066804/intropage_httpd_error.txt)

**Comment by earendilfr** [comment]
OK: i have found a error_log call in my code inserted during development.
Now, you should not seen anymore the message
