### ISSUE TITLE
error if don't have error in log file

### ISSUE THREAD

**Issue by michael067** [earendilfr/plugin_intropage#3]
hi,

i have this error if i don't have error in log file in version 0.92 ( debian 9 )

2017/07/20 10:13:06 - ERROR PHP NOTICE in  Plugin 'intropage': Undefined index: data in file: /var/www/html/cacti/plugins/intropage/display.php  on line: 131
2017/07/20 10:13:06 - CMDPHP PHP ERROR NOTICE Backtrace: (/index.php: 101 api_plugin_hook)(/lib/plugins.php: 73 api_plugin_run_plugin_hook)(/lib/plugins.php: 170 intropage_console_after)(/plugins/intropage/include/settings.php: 61 display_informations)(/plugins/intropage/display.php: 131 CactiErrorHandler)(/lib/functions.php: 4396 cacti_debug_backtrace)

if i delete error in log file, intropage is good one time and this error coming. 

thanks

edit : test with redhat 7.3 ( the same )

2017/07/20 13:24:37 - ERROR PHP NOTICE in Plugin 'intropage': Undefined index: data in file: /opt/rh/httpd24/root/var/www/html/cacti/plugins/intropage/display.php on line: 131
2017/07/20 13:24:37 - CMDPHP PHP ERROR NOTICE Backtrace: (/index.php: 101 api_plugin_hook)(/lib/plugins.php: 69 api_plugin_run_plugin_hook)(/lib/plugins.php: 162 intropage_console_after)(/plugins/intropage/include/settings.php: 61 display_informations)(/plugins/intropage/display.php: 131 CactiErrorHandler)(/lib/functions.php: 4392 cacti_debug_backtrace)

**Comment by earendilfr** [comment]
Could you check with this commit?

**Comment by michael067** [comment]
Perfect :-)
you can close this issue

thanks
