### ISSUE TITLE
Links from intropage to tholds: "breached" "triggered" and "disabled" are incorrect

### ISSUE THREAD

**Issue by ikorzha** [earendilfr/plugin_intropage#5]

**Comment by ikorzha** [comment]
When I click on individual links on intorpage: Breached:  | Trigged:  | Disabled: | I always get "all configured tholds page.
I'm running Cacti 1.1.19 and Thold 1.0.3, Intropage 0.9.2


Instead it should be:
Breached:  plugins/thold/thold_graph.php?action=thold&status=1&data_template_id=-1&host_id=-1&site_id=-1&rows=-1&filter=
Triggered: /plugins/thold/thold_graph.php?action=thold&status=3&data_template_id=-1&host_id=-1&site_id=-1&rows=-1&filter=
Disabled: /plugins/thold/thold_graph.php?action=thold&status=0&data_template_id=-1&host_id=-1&site_id=-1&rows=-1&filter=

**Comment by earendilfr** [comment]
Could you check if it's OK now with the last patch on master branch?

**Comment by ikorzha** [comment]
Confirmed fixed now. Thank you
